---
title: '&#39;Catch&#39; ne peut pas apparaître en dehors d’un &#39;essayez&#39; instruction'
ms.date: 07/20/2015
f1_keywords:
- bc30380
- vbc30380
helpviewer_keywords:
- BC30380
ms.assetid: 73ce950d-881f-4532-8024-40a4930abd32
ms.openlocfilehash: 346852cbd5693fbafe25413291ae284de3692875
ms.sourcegitcommit: 3d5d33f384eeba41b2dff79d096f47ccc8d8f03d
ms.translationtype: MT
ms.contentlocale: fr-FR
ms.lasthandoff: 05/04/2018
ms.locfileid: "33609156"
---
# <a name="39catch39-cannot-appear-outside-a-39try39-statement"></a>&#39;Catch&#39; ne peut pas apparaître en dehors d’un &#39;essayez&#39; instruction
`Catch` doit apparaître dans un bloc d’instruction `Try...Catch...Finally` . Soit vous avez une instruction `Catch` inutile dans votre bloc `Try` , soit votre instruction `Catch` apparaît en dehors des limites de son bloc `Try` .  
  
 **ID d’erreur :** BC30380  
  
## <a name="to-correct-this-error"></a>Pour corriger cette erreur  
  
1.  Supprimez l’instruction `Catch` si elle n’est pas nécessaire, ou placez-la dans un bloc d’instruction `Try...Catch...Finally` .  
  
## <a name="see-also"></a>Voir aussi  
 [Try...Catch...Finally (instruction)](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 
