---
title: L’instruction 'Throw' ne peut pas omettre l’opérande en dehors d’une instruction 'Catch' ou dans une instruction 'Finally'
ms.date: 07/20/2015
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords:
- BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
ms.openlocfilehash: f87c705a8672ba79124c618fbd28e2ef79136b6f
ms.sourcegitcommit: 5c1abeec15fbddcc7dbaa729fabc1f1f29f12045
ms.translationtype: MT
ms.contentlocale: fr-FR
ms.lasthandoff: 03/15/2019
ms.locfileid: "58026245"
---
# <a name="throw-statement-cannot-omit-operand-outside-a-catch-statement-or-inside-a-finally-statement"></a>L’instruction 'Throw' ne peut pas omettre l’opérande en dehors d’une instruction 'Catch' ou dans une instruction 'Finally'
Les instructions`Throw` situées en dehors de l’instruction `Catch` doivent fournir le nom d’un objet exception.  
  
 **ID d’erreur :** BC30666  
  
## <a name="to-correct-this-error"></a>Pour corriger cette erreur  
  
1.  Spécifiez le nom d’un objet d’exception dérivé de `System.Exception`.  
  
2.  Restructurez votre code pour que l’instruction `Throw` se trouve dans un bloc `Catch` .  
  
## <a name="see-also"></a>Voir aussi

- [Throw (instruction)](../../visual-basic/language-reference/statements/throw-statement.md)
- [Try...Catch...Finally (instruction)](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
- <xref:System.Exception?displayProperty=nameWithType>
- [Gestion et levée d’exceptions dans .NET](../../standard/exceptions/index.md)
