---
title: "'Catch' ne peut pas apparaître en dehors d’une instruction 'Try'."
ms.date: 07/20/2015
f1_keywords:
- bc30380
- vbc30380
helpviewer_keywords:
- BC30380
ms.assetid: 73ce950d-881f-4532-8024-40a4930abd32
ms.openlocfilehash: 861057ff4d7c68a5917bddbb8d7361946f3f43f5
ms.sourcegitcommit: 5c1abeec15fbddcc7dbaa729fabc1f1f29f12045
ms.translationtype: MT
ms.contentlocale: fr-FR
ms.lasthandoff: 03/15/2019
ms.locfileid: "58041187"
---
# <a name="catch-cannot-appear-outside-a-try-statement"></a>'Catch' ne peut pas apparaître en dehors d’une instruction 'Try'.
`Catch` doit apparaître dans un bloc d’instruction `Try...Catch...Finally` . Soit vous avez une instruction `Catch` inutile dans votre bloc `Try` , soit votre instruction `Catch` apparaît en dehors des limites de son bloc `Try` .  
  
 **ID d’erreur :** BC30380  
  
## <a name="to-correct-this-error"></a>Pour corriger cette erreur  
  
1.  Supprimez l’instruction `Catch` si elle n’est pas nécessaire, ou placez-la dans un bloc d’instruction `Try...Catch...Finally` .  
  
## <a name="see-also"></a>Voir aussi

- [Try...Catch...Finally (instruction)](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
