---
title: "'Catch' ne peut pas apparaître en dehors d’une instruction 'Try'."
ms.date: 07/20/2015
f1_keywords:
- bc30380
- vbc30380
helpviewer_keywords:
- BC30380
ms.assetid: 73ce950d-881f-4532-8024-40a4930abd32
ms.openlocfilehash: 71b83937edb7f42c9bd62d6fba998d95bb047115
ms.sourcegitcommit: 0888d7b24f475c346a3f444de8d83ec1ca7cd234
ms.translationtype: MT
ms.contentlocale: fr-FR
ms.lasthandoff: 12/22/2018
ms.locfileid: "53776706"
---
# <a name="catch-cannot-appear-outside-a-try-statement"></a>'Catch' ne peut pas apparaître en dehors d’une instruction 'Try'.
`Catch` doit apparaître dans un bloc d’instruction `Try...Catch...Finally`. Soit vous avez une instruction `Catch` inutile dans votre bloc `Try` , soit votre instruction `Catch` apparaît en dehors des limites de son bloc `Try` .  
  
 **ID d’erreur :** BC30380  
  
## <a name="to-correct-this-error"></a>Pour corriger cette erreur  
  
1.  Supprimez l’instruction `Catch` si elle n’est pas nécessaire, ou placez-la dans un bloc d’instruction `Try...Catch...Finally` .  
  
## <a name="see-also"></a>Voir aussi  
 [Try...Catch...Finally (instruction)](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 
